version: "3.7"

services:
    database_postgresql:
        image: postgres
        container_name: cnt_postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=aula02
        volumes:
            - pgdata:/data/postgres
        network_mode: host
    app:
        build: .
        container_name: cnt_aula02
        restart: always
        ports:
            - 3333:3333
        volumes: 
            - .:/usr/app
        network_mode: host
volumes:
    pgdata:
        driver: local